# Generated by Django 2.0.13 on 2019-05-01 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawn_stars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnpostmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
