# Generated by Django 2.0.13 on 2019-04-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn_stars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
