# Generated by Django 2.0.13 on 2019-05-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawn_stars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnphotomodel',
            name='pawn_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pawn_stars_api.PawnPostModel'),
        ),
        migrations.AlterField(
            model_name='pawnphotomodel',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
